//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYT.UI.TescilHizmeti {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gumruk.BizTalk.Integration", ConfigurationName="TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap")]
    public interface Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil", ReplyAction="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil")]
        BYT.UI.TescilHizmeti.TescilSoapOut Tescil(BYT.UI.TescilHizmeti.TescilSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil", ReplyAction="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil")]
        System.Threading.Tasks.Task<BYT.UI.TescilHizmeti.TescilSoapOut> TescilAsync(BYT.UI.TescilHizmeti.TescilSoapIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TescilSoapIn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tescil", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public BYT.UI.TescilHizmeti.TescilSoapInBody Body;
        
        public TescilSoapIn() {
        }
        
        public TescilSoapIn(BYT.UI.TescilHizmeti.TescilSoapInBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class TescilSoapInBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Root;
        
        public TescilSoapInBody() {
        }
        
        public TescilSoapInBody(System.Xml.Linq.XElement Root) {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TescilSoapOut {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TescilResponse", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public BYT.UI.TescilHizmeti.TescilSoapOutBody Body;
        
        public TescilSoapOut() {
        }
        
        public TescilSoapOut(BYT.UI.TescilHizmeti.TescilSoapOutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class TescilSoapOutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Root;
        
        public TescilSoapOutBody() {
        }
        
        public TescilSoapOutBody(System.Xml.Linq.XElement Root) {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapChannel : BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient : System.ServiceModel.ClientBase<BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap>, BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap {
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient() {
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BYT.UI.TescilHizmeti.TescilSoapOut BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap.Tescil(BYT.UI.TescilHizmeti.TescilSoapIn request) {
            return base.Channel.Tescil(request);
        }
        
        public void Tescil(ref System.Xml.Linq.XElement Root) {
            BYT.UI.TescilHizmeti.TescilSoapIn inValue = new BYT.UI.TescilHizmeti.TescilSoapIn();
            inValue.Body = new BYT.UI.TescilHizmeti.TescilSoapInBody();
            inValue.Body.Root = Root;
            BYT.UI.TescilHizmeti.TescilSoapOut retVal = ((BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap)(this)).Tescil(inValue);
            Root = retVal.Body.Root;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BYT.UI.TescilHizmeti.TescilSoapOut> BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap.TescilAsync(BYT.UI.TescilHizmeti.TescilSoapIn request) {
            return base.Channel.TescilAsync(request);
        }
        
        public System.Threading.Tasks.Task<BYT.UI.TescilHizmeti.TescilSoapOut> TescilAsync(System.Xml.Linq.XElement Root) {
            BYT.UI.TescilHizmeti.TescilSoapIn inValue = new BYT.UI.TescilHizmeti.TescilSoapIn();
            inValue.Body = new BYT.UI.TescilHizmeti.TescilSoapInBody();
            inValue.Body.Root = Root;
            return ((BYT.UI.TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap)(this)).TescilAsync(inValue);
        }
    }
}
