//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TescilHizmeti
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gumruk.BizTalk.Integration", ConfigurationName="TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap")]
    public interface Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil", ReplyAction="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_Tescil_PortTescil/Te" +
            "scil")]
        System.Threading.Tasks.Task<TescilHizmeti.TescilSoapOut> TescilAsync(TescilHizmeti.TescilSoapIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TescilSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tescil", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public TescilHizmeti.TescilSoapInBody Body;
        
        public TescilSoapIn()
        {
        }
        
        public TescilSoapIn(TescilHizmeti.TescilSoapInBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class TescilSoapInBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement Root;
        
        public TescilSoapInBody()
        {
        }
        
        public TescilSoapInBody(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TescilSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TescilResponse", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public TescilHizmeti.TescilSoapOutBody Body;
        
        public TescilSoapOut()
        {
        }
        
        public TescilSoapOut(TescilHizmeti.TescilSoapOutBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class TescilSoapOutBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement Root;
        
        public TescilSoapOutBody()
        {
        }
        
        public TescilSoapOutBody(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapChannel : TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient : System.ServiceModel.ClientBase<TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap>, TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient() : 
                base(Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetDefaultBinding(), Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetBindingForEndpoint(endpointConfiguration), Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TescilHizmeti.TescilSoapOut> TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap.TescilAsync(TescilHizmeti.TescilSoapIn request)
        {
            return base.Channel.TescilAsync(request);
        }
        
        public System.Threading.Tasks.Task<TescilHizmeti.TescilSoapOut> TescilAsync(System.Xml.XmlElement Root)
        {
            TescilHizmeti.TescilSoapIn inValue = new TescilHizmeti.TescilSoapIn();
            inValue.Body = new TescilHizmeti.TescilSoapInBody();
            inValue.Body.Root = Root;
            return ((TescilHizmeti.Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap)(this)).TescilAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wstest.gtb.gov.tr:8080/EXT/Gumruk/EGE/Provider/TescilWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoapClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Gumruk_Biztalk_EImzaTescil_Tescil_PortTescilSoap,
        }
    }
}
