//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesaiHizmeti
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesaiBasvuru", Namespace="http://MesaiBasvuru")]
    public partial class MesaiBasvuru : object
    {
        
        private string KullaniciAdiField;
        
        private string SifreField;
        
        private string RefIDField;
        
        private string IPField;
        
        private string IslemTipiField;
        
        private string DigerNoField;
        
        private string BeyannameNoField;
        
        private string IrtibatAdSoyadField;
        
        private string IrtibatTelefonNoField;
        
        private string GumrukSahasindaField;
        
        private System.DateTime BaslangicZamaniField;
        
        private string AdresField;
        
        private int UzaklikField;
        
        private string GlobalHesaptanOdemeField;
        
        private string GlobalHesapIDField;
        
        private string GumrukKoduField;
        
        private string EsyaninBulunduguYerField;
        
        private string EsyaninBulunduguYerAdiField;
        
        private string EsyaninBulunduguYerKoduField;
        
        private string FirmaVergiNoField;
        
        private string OdemeYapacakFirmaVergiNoField;
        
        private int OZBYSayisiField;
        
        private int NCTSSayisiField;
        
        private int AracAdediField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi
        {
            get
            {
                return this.KullaniciAdiField;
            }
            set
            {
                this.KullaniciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IslemTipi
        {
            get
            {
                return this.IslemTipiField;
            }
            set
            {
                this.IslemTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DigerNo
        {
            get
            {
                return this.DigerNoField;
            }
            set
            {
                this.DigerNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BeyannameNo
        {
            get
            {
                return this.BeyannameNoField;
            }
            set
            {
                this.BeyannameNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string IrtibatAdSoyad
        {
            get
            {
                return this.IrtibatAdSoyadField;
            }
            set
            {
                this.IrtibatAdSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IrtibatTelefonNo
        {
            get
            {
                return this.IrtibatTelefonNoField;
            }
            set
            {
                this.IrtibatTelefonNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string GumrukSahasinda
        {
            get
            {
                return this.GumrukSahasindaField;
            }
            set
            {
                this.GumrukSahasindaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime BaslangicZamani
        {
            get
            {
                return this.BaslangicZamaniField;
            }
            set
            {
                this.BaslangicZamaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Uzaklik
        {
            get
            {
                return this.UzaklikField;
            }
            set
            {
                this.UzaklikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string GlobalHesaptanOdeme
        {
            get
            {
                return this.GlobalHesaptanOdemeField;
            }
            set
            {
                this.GlobalHesaptanOdemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string GlobalHesapID
        {
            get
            {
                return this.GlobalHesapIDField;
            }
            set
            {
                this.GlobalHesapIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string GumrukKodu
        {
            get
            {
                return this.GumrukKoduField;
            }
            set
            {
                this.GumrukKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string EsyaninBulunduguYer
        {
            get
            {
                return this.EsyaninBulunduguYerField;
            }
            set
            {
                this.EsyaninBulunduguYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string EsyaninBulunduguYerAdi
        {
            get
            {
                return this.EsyaninBulunduguYerAdiField;
            }
            set
            {
                this.EsyaninBulunduguYerAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string EsyaninBulunduguYerKodu
        {
            get
            {
                return this.EsyaninBulunduguYerKoduField;
            }
            set
            {
                this.EsyaninBulunduguYerKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string FirmaVergiNo
        {
            get
            {
                return this.FirmaVergiNoField;
            }
            set
            {
                this.FirmaVergiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string OdemeYapacakFirmaVergiNo
        {
            get
            {
                return this.OdemeYapacakFirmaVergiNoField;
            }
            set
            {
                this.OdemeYapacakFirmaVergiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int OZBYSayisi
        {
            get
            {
                return this.OZBYSayisiField;
            }
            set
            {
                this.OZBYSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int NCTSSayisi
        {
            get
            {
                return this.NCTSSayisiField;
            }
            set
            {
                this.NCTSSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int AracAdedi
        {
            get
            {
                return this.AracAdediField;
            }
            set
            {
                this.AracAdediField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MesaiBasvuruIptal", Namespace="http://MesaiBasvuruIptal")]
    public partial class MesaiBasvuruIptal : object
    {
        
        private string KullaniciAdiField;
        
        private string SifreField;
        
        private string RefIDField;
        
        private string IPField;
        
        private string MesaiIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi
        {
            get
            {
                return this.KullaniciAdiField;
            }
            set
            {
                this.KullaniciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MesaiID
        {
            get
            {
                return this.MesaiIDField;
            }
            set
            {
                this.MesaiIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalHesapBasvuru", Namespace="http://GlobalHesapBasvuru")]
    public partial class GlobalHesapBasvuru : object
    {
        
        private string KullaniciAdiField;
        
        private string SifreField;
        
        private string RefIDField;
        
        private string IPField;
        
        private string AdresField;
        
        private decimal TutarField;
        
        private string OdemeYapacakFirmaVergiNoField;
        
        private string GumrukKoduField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi
        {
            get
            {
                return this.KullaniciAdiField;
            }
            set
            {
                this.KullaniciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Tutar
        {
            get
            {
                return this.TutarField;
            }
            set
            {
                this.TutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OdemeYapacakFirmaVergiNo
        {
            get
            {
                return this.OdemeYapacakFirmaVergiNoField;
            }
            set
            {
                this.OdemeYapacakFirmaVergiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GumrukKodu
        {
            get
            {
                return this.GumrukKoduField;
            }
            set
            {
                this.GumrukKoduField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalHesapBasvuruIptal", Namespace="http://GlobalHesapBasvuruIptal")]
    public partial class GlobalHesapBasvuruIptal : object
    {
        
        private string KullaniciAdiField;
        
        private string SifreField;
        
        private string RefIDField;
        
        private string IPField;
        
        private string HesapIDField;
        
        private string OdemeYapacakFirmaVergiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi
        {
            get
            {
                return this.KullaniciAdiField;
            }
            set
            {
                this.KullaniciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HesapID
        {
            get
            {
                return this.HesapIDField;
            }
            set
            {
                this.HesapIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OdemeYapacakFirmaVergiNo
        {
            get
            {
                return this.OdemeYapacakFirmaVergiNoField;
            }
            set
            {
                this.OdemeYapacakFirmaVergiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalHesapBakiyeTransfer", Namespace="http://GlobalHesapBakiyeTransfer")]
    public partial class GlobalHesapBakiyeTransfer : object
    {
        
        private string KullaniciAdiField;
        
        private string SifreField;
        
        private string RefIDField;
        
        private string IPField;
        
        private string HesapSahibiFirmaVergiNoField;
        
        private string KaynakHesapIDField;
        
        private string HedefHesapIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi
        {
            get
            {
                return this.KullaniciAdiField;
            }
            set
            {
                this.KullaniciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RefID
        {
            get
            {
                return this.RefIDField;
            }
            set
            {
                this.RefIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HesapSahibiFirmaVergiNo
        {
            get
            {
                return this.HesapSahibiFirmaVergiNoField;
            }
            set
            {
                this.HesapSahibiFirmaVergiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string KaynakHesapID
        {
            get
            {
                return this.KaynakHesapIDField;
            }
            set
            {
                this.KaynakHesapIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HedefHesapID
        {
            get
            {
                return this.HedefHesapIDField;
            }
            set
            {
                this.HedefHesapIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MesaiHizmeti.IMesaiHizmeti")]
    public interface IMesaiHizmeti
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaiHizmeti/MesaiBasvurusuYap", ReplyAction="http://tempuri.org/IMesaiHizmeti/MesaiBasvurusuYapResponse")]
        System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruSoapOut> MesaiBasvurusuYapAsync(MesaiHizmeti.MesaiBasvuruSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaiHizmeti/MesaiBasvuruIptal", ReplyAction="http://tempuri.org/IMesaiHizmeti/MesaiBasvuruIptalResponse")]
        System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruIptalSoapOut> MesaiBasvuruIptalAsync(MesaiHizmeti.MesaiBasvuruIptalSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaiHizmeti/GlobalHesapBasvuruYap", ReplyAction="http://tempuri.org/IMesaiHizmeti/GlobalHesapBasvuruYapResponse")]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruSoapOut> GlobalHesapBasvuruYapAsync(MesaiHizmeti.GlobalHesapBasvuruSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaiHizmeti/GlobalHesapBasvuruIptal", ReplyAction="http://tempuri.org/IMesaiHizmeti/GlobalHesapBasvuruIptalResponse")]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruIptalSoapOut> GlobalHesapBasvuruIptalAsync(MesaiHizmeti.GlobalHesapBasvuruIptalSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaiHizmeti/GlobalHesapBakiyeTransfer", ReplyAction="http://tempuri.org/IMesaiHizmeti/GlobalHesapBakiyeTransferResponse")]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBakiyeTransferSoapOut> GlobalHesapBakiyeTransferAsync(MesaiHizmeti.GlobalHesapBakiyeTransferSoapIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MesaiBasvuru", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MesaiBasvuruSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MesaiBasvuru", Order=0)]
        public MesaiHizmeti.MesaiBasvuru GelenBasvuruBilgisi;
        
        public MesaiBasvuruSoapIn()
        {
        }
        
        public MesaiBasvuruSoapIn(MesaiHizmeti.MesaiBasvuru GelenBasvuruBilgisi)
        {
            this.GelenBasvuruBilgisi = GelenBasvuruBilgisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FazlaMesaiBasvuruResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MesaiBasvuruSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement Root;
        
        public MesaiBasvuruSoapOut()
        {
        }
        
        public MesaiBasvuruSoapOut(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MesaiBasvuruIptal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MesaiBasvuruIptalSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MesaiBasvuruIptal", Order=0)]
        public MesaiHizmeti.MesaiBasvuruIptal GelenBasvuruIptalBilgisi;
        
        public MesaiBasvuruIptalSoapIn()
        {
        }
        
        public MesaiBasvuruIptalSoapIn(MesaiHizmeti.MesaiBasvuruIptal GelenBasvuruIptalBilgisi)
        {
            this.GelenBasvuruIptalBilgisi = GelenBasvuruIptalBilgisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FazlaMesaiBasvuruIptalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MesaiBasvuruIptalSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement Root;
        
        public MesaiBasvuruIptalSoapOut()
        {
        }
        
        public MesaiBasvuruIptalSoapOut(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GlobalHesapBasvuru", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GlobalHesapBasvuruSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://GlobalHesapBasvuru", Order=0)]
        public MesaiHizmeti.GlobalHesapBasvuru GelenGlobalHesapBasvuruBilgisi;
        
        public GlobalHesapBasvuruSoapIn()
        {
        }
        
        public GlobalHesapBasvuruSoapIn(MesaiHizmeti.GlobalHesapBasvuru GelenGlobalHesapBasvuruBilgisi)
        {
            this.GelenGlobalHesapBasvuruBilgisi = GelenGlobalHesapBasvuruBilgisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GlobalHesapBasvuruResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GlobalHesapBasvuruSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement Root;
        
        public GlobalHesapBasvuruSoapOut()
        {
        }
        
        public GlobalHesapBasvuruSoapOut(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GlobalHesapBasvuruIptalSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GlobalHesapBasvuruIptal", Namespace="http://tempuri.org/", Order=0)]
        public MesaiHizmeti.GlobalHesapBasvuruIptalSoapInBody Body;
        
        public GlobalHesapBasvuruIptalSoapIn()
        {
        }
        
        public GlobalHesapBasvuruIptalSoapIn(MesaiHizmeti.GlobalHesapBasvuruIptalSoapInBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GlobalHesapBasvuruIptal")]
    public partial class GlobalHesapBasvuruIptalSoapInBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MesaiHizmeti.GlobalHesapBasvuruIptal GelenGlobalHesapIptalBilgisi;
        
        public GlobalHesapBasvuruIptalSoapInBody()
        {
        }
        
        public GlobalHesapBasvuruIptalSoapInBody(MesaiHizmeti.GlobalHesapBasvuruIptal GelenGlobalHesapIptalBilgisi)
        {
            this.GelenGlobalHesapIptalBilgisi = GelenGlobalHesapIptalBilgisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GlobalHesapBasvuruIptalSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GlobalHesapBasvuruIptalResponse", Namespace="http://tempuri.org/", Order=0)]
        public MesaiHizmeti.GlobalHesapBasvuruIptalSoapOutBody Body;
        
        public GlobalHesapBasvuruIptalSoapOut()
        {
        }
        
        public GlobalHesapBasvuruIptalSoapOut(MesaiHizmeti.GlobalHesapBasvuruIptalSoapOutBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GlobalHesapBasvuruIptalSoapOutBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement Root;
        
        public GlobalHesapBasvuruIptalSoapOutBody()
        {
        }
        
        public GlobalHesapBasvuruIptalSoapOutBody(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GlobalHesapBakiyeTransferSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GlobalHesapBakiyeTransfer", Namespace="http://tempuri.org/", Order=0)]
        public MesaiHizmeti.GlobalHesapBakiyeTransferSoapInBody Body;
        
        public GlobalHesapBakiyeTransferSoapIn()
        {
        }
        
        public GlobalHesapBakiyeTransferSoapIn(MesaiHizmeti.GlobalHesapBakiyeTransferSoapInBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GlobalHesapBakiyeTransfer")]
    public partial class GlobalHesapBakiyeTransferSoapInBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MesaiHizmeti.GlobalHesapBakiyeTransfer GlobalHesapBakiyeTransfer;
        
        public GlobalHesapBakiyeTransferSoapInBody()
        {
        }
        
        public GlobalHesapBakiyeTransferSoapInBody(MesaiHizmeti.GlobalHesapBakiyeTransfer GlobalHesapBakiyeTransfer)
        {
            this.GlobalHesapBakiyeTransfer = GlobalHesapBakiyeTransfer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GlobalHesapBakiyeTransferSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GlobalHesapBakiyeTransferResponse", Namespace="http://tempuri.org/", Order=0)]
        public MesaiHizmeti.GlobalHesapBakiyeTransferSoapOutBody Body;
        
        public GlobalHesapBakiyeTransferSoapOut()
        {
        }
        
        public GlobalHesapBakiyeTransferSoapOut(MesaiHizmeti.GlobalHesapBakiyeTransferSoapOutBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GlobalHesapBakiyeTransferSoapOutBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement Root;
        
        public GlobalHesapBakiyeTransferSoapOutBody()
        {
        }
        
        public GlobalHesapBakiyeTransferSoapOutBody(System.Xml.XmlElement Root)
        {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMesaiHizmetiChannel : MesaiHizmeti.IMesaiHizmeti, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MesaiHizmetiClient : System.ServiceModel.ClientBase<MesaiHizmeti.IMesaiHizmeti>, MesaiHizmeti.IMesaiHizmeti
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MesaiHizmetiClient(EndpointConfiguration endpointConfiguration) : 
                base(MesaiHizmetiClient.GetBindingForEndpoint(endpointConfiguration), MesaiHizmetiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MesaiHizmetiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MesaiHizmetiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MesaiHizmetiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MesaiHizmetiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MesaiHizmetiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruSoapOut> MesaiHizmeti.IMesaiHizmeti.MesaiBasvurusuYapAsync(MesaiHizmeti.MesaiBasvuruSoapIn request)
        {
            return base.Channel.MesaiBasvurusuYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruSoapOut> MesaiBasvurusuYapAsync(MesaiHizmeti.MesaiBasvuru GelenBasvuruBilgisi)
        {
            MesaiHizmeti.MesaiBasvuruSoapIn inValue = new MesaiHizmeti.MesaiBasvuruSoapIn();
            inValue.GelenBasvuruBilgisi = GelenBasvuruBilgisi;
            return ((MesaiHizmeti.IMesaiHizmeti)(this)).MesaiBasvurusuYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruIptalSoapOut> MesaiHizmeti.IMesaiHizmeti.MesaiBasvuruIptalAsync(MesaiHizmeti.MesaiBasvuruIptalSoapIn request)
        {
            return base.Channel.MesaiBasvuruIptalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesaiHizmeti.MesaiBasvuruIptalSoapOut> MesaiBasvuruIptalAsync(MesaiHizmeti.MesaiBasvuruIptal GelenBasvuruIptalBilgisi)
        {
            MesaiHizmeti.MesaiBasvuruIptalSoapIn inValue = new MesaiHizmeti.MesaiBasvuruIptalSoapIn();
            inValue.GelenBasvuruIptalBilgisi = GelenBasvuruIptalBilgisi;
            return ((MesaiHizmeti.IMesaiHizmeti)(this)).MesaiBasvuruIptalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruSoapOut> MesaiHizmeti.IMesaiHizmeti.GlobalHesapBasvuruYapAsync(MesaiHizmeti.GlobalHesapBasvuruSoapIn request)
        {
            return base.Channel.GlobalHesapBasvuruYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruSoapOut> GlobalHesapBasvuruYapAsync(MesaiHizmeti.GlobalHesapBasvuru GelenGlobalHesapBasvuruBilgisi)
        {
            MesaiHizmeti.GlobalHesapBasvuruSoapIn inValue = new MesaiHizmeti.GlobalHesapBasvuruSoapIn();
            inValue.GelenGlobalHesapBasvuruBilgisi = GelenGlobalHesapBasvuruBilgisi;
            return ((MesaiHizmeti.IMesaiHizmeti)(this)).GlobalHesapBasvuruYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruIptalSoapOut> MesaiHizmeti.IMesaiHizmeti.GlobalHesapBasvuruIptalAsync(MesaiHizmeti.GlobalHesapBasvuruIptalSoapIn request)
        {
            return base.Channel.GlobalHesapBasvuruIptalAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBasvuruIptalSoapOut> GlobalHesapBasvuruIptalAsync(MesaiHizmeti.GlobalHesapBasvuruIptal GelenGlobalHesapIptalBilgisi)
        {
            MesaiHizmeti.GlobalHesapBasvuruIptalSoapIn inValue = new MesaiHizmeti.GlobalHesapBasvuruIptalSoapIn();
            inValue.Body = new MesaiHizmeti.GlobalHesapBasvuruIptalSoapInBody();
            inValue.Body.GelenGlobalHesapIptalBilgisi = GelenGlobalHesapIptalBilgisi;
            return ((MesaiHizmeti.IMesaiHizmeti)(this)).GlobalHesapBasvuruIptalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBakiyeTransferSoapOut> MesaiHizmeti.IMesaiHizmeti.GlobalHesapBakiyeTransferAsync(MesaiHizmeti.GlobalHesapBakiyeTransferSoapIn request)
        {
            return base.Channel.GlobalHesapBakiyeTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<MesaiHizmeti.GlobalHesapBakiyeTransferSoapOut> GlobalHesapBakiyeTransferAsync(MesaiHizmeti.GlobalHesapBakiyeTransfer GlobalHesapBakiyeTransfer)
        {
            MesaiHizmeti.GlobalHesapBakiyeTransferSoapIn inValue = new MesaiHizmeti.GlobalHesapBakiyeTransferSoapIn();
            inValue.Body = new MesaiHizmeti.GlobalHesapBakiyeTransferSoapInBody();
            inValue.Body.GlobalHesapBakiyeTransfer = GlobalHesapBakiyeTransfer;
            return ((MesaiHizmeti.IMesaiHizmeti)(this)).GlobalHesapBakiyeTransferAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMesaiHizmeti))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMesaiHizmeti))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMesaiHizmeti))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.gtb.gov.tr:8080/EXT/Gumruk/EGE/Provider/FazlaMesaiWS");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IMesaiHizmeti))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.gtb.gov.tr:8080/EXT/Gumruk/EGE/Provider/FazlaMesaiWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMesaiHizmeti,
            
            BasicHttpsBinding_IMesaiHizmeti,
        }
    }
}
