//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGHBHizmeti
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gumruk.BizTalk.Integration", ConfigurationName="IGHBHizmeti.Gumruk_Biztalk_IGHB")]
    public interface Gumruk_Biztalk_IGHB
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi", ReplyAction="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<IGHBHizmeti.IGHBSoapOut> IzinliGondericiHazirBildirimiYapAsync(IGHBHizmeti.IGHBSoapIn request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://LoginKontrol.IGHBGelen")]
    public partial class IGHBGelen
    {
        
        private string refIDField;
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        private IGHB iGHBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RefID
        {
            get
            {
                return this.refIDField;
            }
            set
            {
                this.refIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KullaniciAdi
        {
            get
            {
                return this.kullaniciAdiField;
            }
            set
            {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sifre
        {
            get
            {
                return this.sifreField;
            }
            set
            {
                this.sifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", IsNullable=true, Order=3)]
        public IGHB IGHB
        {
            get
            {
                return this.iGHBField;
            }
            set
            {
                this.iGHBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IGHB
    {
        
        private string tesisKoduField;
        
        private string izinliGondericiVergiNoField;
        
        private string gumrukKoduField;
        
        private string plakaBilgisiField;
        
        private string ePostaField;
        
        private TCGBBilgi[] tCGBBilgiListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TesisKodu
        {
            get
            {
                return this.tesisKoduField;
            }
            set
            {
                this.tesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IzinliGondericiVergiNo
        {
            get
            {
                return this.izinliGondericiVergiNoField;
            }
            set
            {
                this.izinliGondericiVergiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GumrukKodu
        {
            get
            {
                return this.gumrukKoduField;
            }
            set
            {
                this.gumrukKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PlakaBilgisi
        {
            get
            {
                return this.plakaBilgisiField;
            }
            set
            {
                this.plakaBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EPosta
        {
            get
            {
                return this.ePostaField;
            }
            set
            {
                this.ePostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        public TCGBBilgi[] TCGBBilgiListesi
        {
            get
            {
                return this.tCGBBilgiListesiField;
            }
            set
            {
                this.tCGBBilgiListesiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGBBilgi
    {
        
        private string tCGBNumarasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TCGBNumarasi
        {
            get
            {
                return this.tCGBNumarasiField;
            }
            set
            {
                this.tCGBNumarasiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IGHB", WrapperNamespace="http://Gumruk.BizTalk.Integration", IsWrapped=true)]
    public partial class IGHBSoapIn
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://LoginKontrol.IGHBGelen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://LoginKontrol.IGHBGelen")]
        public IGHBHizmeti.IGHBGelen IGHBGelen;
        
        public IGHBSoapIn()
        {
        }
        
        public IGHBSoapIn(IGHBHizmeti.IGHBGelen IGHBGelen)
        {
            this.IGHBGelen = IGHBGelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IGHBResponse", WrapperNamespace="http://Gumruk.BizTalk.Integration", IsWrapped=true)]
    public partial class IGHBSoapOut
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
        public System.Xml.XmlNode Root;
        
        public IGHBSoapOut()
        {
        }
        
        public IGHBSoapOut(System.Xml.XmlNode Root)
        {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Gumruk_Biztalk_IGHBChannel : IGHBHizmeti.Gumruk_Biztalk_IGHB, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Gumruk_Biztalk_IGHBClient : System.ServiceModel.ClientBase<IGHBHizmeti.Gumruk_Biztalk_IGHB>, IGHBHizmeti.Gumruk_Biztalk_IGHB
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Gumruk_Biztalk_IGHBClient(EndpointConfiguration endpointConfiguration) : 
                base(Gumruk_Biztalk_IGHBClient.GetBindingForEndpoint(endpointConfiguration), Gumruk_Biztalk_IGHBClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_IGHBClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Gumruk_Biztalk_IGHBClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_IGHBClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Gumruk_Biztalk_IGHBClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Gumruk_Biztalk_IGHBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IGHBHizmeti.IGHBSoapOut> IGHBHizmeti.Gumruk_Biztalk_IGHB.IzinliGondericiHazirBildirimiYapAsync(IGHBHizmeti.IGHBSoapIn request)
        {
            return base.Channel.IzinliGondericiHazirBildirimiYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<IGHBHizmeti.IGHBSoapOut> IzinliGondericiHazirBildirimiYapAsync(IGHBHizmeti.IGHBGelen IGHBGelen)
        {
            IGHBHizmeti.IGHBSoapIn inValue = new IGHBHizmeti.IGHBSoapIn();
            inValue.IGHBGelen = IGHBGelen;
            return ((IGHBHizmeti.Gumruk_Biztalk_IGHB)(this)).IzinliGondericiHazirBildirimiYapAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_IGHB))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_Gumruk_Biztalk_IGHB))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Gumruk_Biztalk_IGHB))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.gtb.gov.tr:8080/EXT/Gumruk/EGE/Provider/IGHB");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_Gumruk_Biztalk_IGHB))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.gtb.gov.tr:8080/EXT/Gumruk/EGE/Provider/IGHB");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Gumruk_Biztalk_IGHB,
            
            BasicHttpsBinding_Gumruk_Biztalk_IGHB,
        }
    }
}
