//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferansVerileri
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferansVerileri.IGumrukReferansVerileri")]
    public interface IGumrukReferansVerileri
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/ReferansVerisiGetir", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/ReferansVerisiGetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.ReferansVerisiGetirResponse> ReferansVerisiGetirAsync(ReferansVerileri.ReferansVerisiGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/OZBYBeyannamesiDogrumu", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/OZBYBeyannamesiDogrumuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.OZBYBeyannamesiDogrumuResponse> OZBYBeyannamesiDogrumuAsync(ReferansVerileri.OZBYBeyannamesiDogrumuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/NCTS_OZBYKontrol", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/NCTS_OZBYKontrolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.NCTS_OZBYKontrolResponse> NCTS_OZBYKontrolAsync(ReferansVerileri.NCTS_OZBYKontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/TasimaSenetleriGetir", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/TasimaSenetleriGetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.TasimaSenetleriGetirResponse> TasimaSenetleriGetirAsync(ReferansVerileri.TasimaSenetleriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/TarifeGetir", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/TarifeGetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.TarifeGetirResponse> TarifeGetirAsync(ReferansVerileri.TarifeGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/FirmaBilgisiGetir", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/FirmaBilgisiGetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.FirmaBilgisiGetirResponse> FirmaBilgisiGetirAsync(ReferansVerileri.FirmaBilgisiGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/BankaBilgisiGetir", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/BankaBilgisiGetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.BankaBilgisiGetirResponse> BankaBilgisiGetirAsync(ReferansVerileri.BankaBilgisiGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGumrukReferansVerileri/AntrepoBeyannamesiDogrumu", ReplyAction="http://tempuri.org/IGumrukReferansVerileri/AntrepoBeyannamesiDogrumuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReferansVerileri.AntrepoBeyannamesiDogrumuResponse> AntrepoBeyannamesiDogrumuAsync(ReferansVerileri.AntrepoBeyannamesiDogrumuRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Gov.GTB.GumrukReferansVerileri.TYPES")]
    public partial class FirmaBilgi
    {
        
        private string adi_unvaniField;
        
        private string cadde_s_noField;
        
        private string faksField;
        
        private string il_ilceField;
        
        private string posta_koduField;
        
        private string telefonField;
        
        private string tipField;
        
        private string ulke_koduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Adi_unvani
        {
            get
            {
                return this.adi_unvaniField;
            }
            set
            {
                this.adi_unvaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cadde_s_no
        {
            get
            {
                return this.cadde_s_noField;
            }
            set
            {
                this.cadde_s_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Faks
        {
            get
            {
                return this.faksField;
            }
            set
            {
                this.faksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Il_ilce
        {
            get
            {
                return this.il_ilceField;
            }
            set
            {
                this.il_ilceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Posta_kodu
        {
            get
            {
                return this.posta_koduField;
            }
            set
            {
                this.posta_koduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Tip
        {
            get
            {
                return this.tipField;
            }
            set
            {
                this.tipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Ulke_kodu
        {
            get
            {
                return this.ulke_koduField;
            }
            set
            {
                this.ulke_koduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Gov.GTB.GumrukReferansVerileri.TYPES")]
    public partial class TasimaSenedi
    {
        
        private string tasimaSenedi_Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TasimaSenedi_
        {
            get
            {
                return this.tasimaSenedi_Field;
            }
            set
            {
                this.tasimaSenedi_Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReferansVerisiGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReferansVerisiGetirRequest
    {
        
        public ReferansVerisiGetirRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReferansVerisiGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReferansVerisiGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferansVerileri.ArrayOfXElement ReferansVerisiGetirResult;
        
        public ReferansVerisiGetirResponse()
        {
        }
        
        public ReferansVerisiGetirResponse(ReferansVerileri.ArrayOfXElement ReferansVerisiGetirResult)
        {
            this.ReferansVerisiGetirResult = ReferansVerisiGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OZBYBeyannamesiDogrumu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OZBYBeyannamesiDogrumuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OZBYBeyannamesiNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gumruk;
        
        public OZBYBeyannamesiDogrumuRequest()
        {
        }
        
        public OZBYBeyannamesiDogrumuRequest(string OZBYBeyannamesiNo, string gumruk)
        {
            this.OZBYBeyannamesiNo = OZBYBeyannamesiNo;
            this.gumruk = gumruk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OZBYBeyannamesiDogrumuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OZBYBeyannamesiDogrumuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OZBYBeyannamesiDogrumuResult;
        
        public OZBYBeyannamesiDogrumuResponse()
        {
        }
        
        public OZBYBeyannamesiDogrumuResponse(string OZBYBeyannamesiDogrumuResult)
        {
            this.OZBYBeyannamesiDogrumuResult = OZBYBeyannamesiDogrumuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NCTS_OZBYKontrol", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NCTS_OZBYKontrolRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OZBYBeyannamesiNo;
        
        public NCTS_OZBYKontrolRequest()
        {
        }
        
        public NCTS_OZBYKontrolRequest(string OZBYBeyannamesiNo)
        {
            this.OZBYBeyannamesiNo = OZBYBeyannamesiNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NCTS_OZBYKontrolResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NCTS_OZBYKontrolResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NCTS_OZBYKontrolResult;
        
        public NCTS_OZBYKontrolResponse()
        {
        }
        
        public NCTS_OZBYKontrolResponse(string NCTS_OZBYKontrolResult)
        {
            this.NCTS_OZBYKontrolResult = NCTS_OZBYKontrolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TasimaSenetleriGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TasimaSenetleriGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OzetBeyanNo;
        
        public TasimaSenetleriGetirRequest()
        {
        }
        
        public TasimaSenetleriGetirRequest(string OzetBeyanNo)
        {
            this.OzetBeyanNo = OzetBeyanNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TasimaSenetleriGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TasimaSenetleriGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Gov.GTB.GumrukReferansVerileri.TYPES")]
        public ReferansVerileri.TasimaSenedi[] TasimaSenetleriGetirResult;
        
        public TasimaSenetleriGetirResponse()
        {
        }
        
        public TasimaSenetleriGetirResponse(ReferansVerileri.TasimaSenedi[] TasimaSenetleriGetirResult)
        {
            this.TasimaSenetleriGetirResult = TasimaSenetleriGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TarifeGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TarifeGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GTIP;
        
        public TarifeGetirRequest()
        {
        }
        
        public TarifeGetirRequest(string GTIP)
        {
            this.GTIP = GTIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TarifeGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TarifeGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TarifeGetirResult;
        
        public TarifeGetirResponse()
        {
        }
        
        public TarifeGetirResponse(string TarifeGetirResult)
        {
            this.TarifeGetirResult = TarifeGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FirmaBilgisiGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FirmaBilgisiGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirmaKimlikNo;
        
        public FirmaBilgisiGetirRequest()
        {
        }
        
        public FirmaBilgisiGetirRequest(string FirmaKimlikNo)
        {
            this.FirmaKimlikNo = FirmaKimlikNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FirmaBilgisiGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FirmaBilgisiGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferansVerileri.FirmaBilgi FirmaBilgisiGetirResult;
        
        public FirmaBilgisiGetirResponse()
        {
        }
        
        public FirmaBilgisiGetirResponse(ReferansVerileri.FirmaBilgi FirmaBilgisiGetirResult)
        {
            this.FirmaBilgisiGetirResult = FirmaBilgisiGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BankaBilgisiGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BankaBilgisiGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bankaKodu;
        
        public BankaBilgisiGetirRequest()
        {
        }
        
        public BankaBilgisiGetirRequest(string bankaKodu)
        {
            this.bankaKodu = bankaKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BankaBilgisiGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BankaBilgisiGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BankaBilgisiGetirResult;
        
        public BankaBilgisiGetirResponse()
        {
        }
        
        public BankaBilgisiGetirResponse(string BankaBilgisiGetirResult)
        {
            this.BankaBilgisiGetirResult = BankaBilgisiGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AntrepoBeyannamesiDogrumu", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AntrepoBeyannamesiDogrumuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string antrepoBeyannamesiNo;
        
        public AntrepoBeyannamesiDogrumuRequest()
        {
        }
        
        public AntrepoBeyannamesiDogrumuRequest(string antrepoBeyannamesiNo)
        {
            this.antrepoBeyannamesiNo = antrepoBeyannamesiNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AntrepoBeyannamesiDogrumuResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AntrepoBeyannamesiDogrumuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AntrepoBeyannamesiDogrumuResult;
        
        public AntrepoBeyannamesiDogrumuResponse()
        {
        }
        
        public AntrepoBeyannamesiDogrumuResponse(string AntrepoBeyannamesiDogrumuResult)
        {
            this.AntrepoBeyannamesiDogrumuResult = AntrepoBeyannamesiDogrumuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IGumrukReferansVerileriChannel : ReferansVerileri.IGumrukReferansVerileri, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GumrukReferansVerileriClient : System.ServiceModel.ClientBase<ReferansVerileri.IGumrukReferansVerileri>, ReferansVerileri.IGumrukReferansVerileri
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GumrukReferansVerileriClient() : 
                base(GumrukReferansVerileriClient.GetDefaultBinding(), GumrukReferansVerileriClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGumrukReferansVerileri.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GumrukReferansVerileriClient(EndpointConfiguration endpointConfiguration) : 
                base(GumrukReferansVerileriClient.GetBindingForEndpoint(endpointConfiguration), GumrukReferansVerileriClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GumrukReferansVerileriClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GumrukReferansVerileriClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GumrukReferansVerileriClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GumrukReferansVerileriClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GumrukReferansVerileriClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.ReferansVerisiGetirResponse> ReferansVerileri.IGumrukReferansVerileri.ReferansVerisiGetirAsync(ReferansVerileri.ReferansVerisiGetirRequest request)
        {
            return base.Channel.ReferansVerisiGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.ReferansVerisiGetirResponse> ReferansVerisiGetirAsync()
        {
            ReferansVerileri.ReferansVerisiGetirRequest inValue = new ReferansVerileri.ReferansVerisiGetirRequest();
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).ReferansVerisiGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.OZBYBeyannamesiDogrumuResponse> ReferansVerileri.IGumrukReferansVerileri.OZBYBeyannamesiDogrumuAsync(ReferansVerileri.OZBYBeyannamesiDogrumuRequest request)
        {
            return base.Channel.OZBYBeyannamesiDogrumuAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.OZBYBeyannamesiDogrumuResponse> OZBYBeyannamesiDogrumuAsync(string OZBYBeyannamesiNo, string gumruk)
        {
            ReferansVerileri.OZBYBeyannamesiDogrumuRequest inValue = new ReferansVerileri.OZBYBeyannamesiDogrumuRequest();
            inValue.OZBYBeyannamesiNo = OZBYBeyannamesiNo;
            inValue.gumruk = gumruk;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).OZBYBeyannamesiDogrumuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.NCTS_OZBYKontrolResponse> ReferansVerileri.IGumrukReferansVerileri.NCTS_OZBYKontrolAsync(ReferansVerileri.NCTS_OZBYKontrolRequest request)
        {
            return base.Channel.NCTS_OZBYKontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.NCTS_OZBYKontrolResponse> NCTS_OZBYKontrolAsync(string OZBYBeyannamesiNo)
        {
            ReferansVerileri.NCTS_OZBYKontrolRequest inValue = new ReferansVerileri.NCTS_OZBYKontrolRequest();
            inValue.OZBYBeyannamesiNo = OZBYBeyannamesiNo;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).NCTS_OZBYKontrolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.TasimaSenetleriGetirResponse> ReferansVerileri.IGumrukReferansVerileri.TasimaSenetleriGetirAsync(ReferansVerileri.TasimaSenetleriGetirRequest request)
        {
            return base.Channel.TasimaSenetleriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.TasimaSenetleriGetirResponse> TasimaSenetleriGetirAsync(string OzetBeyanNo)
        {
            ReferansVerileri.TasimaSenetleriGetirRequest inValue = new ReferansVerileri.TasimaSenetleriGetirRequest();
            inValue.OzetBeyanNo = OzetBeyanNo;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).TasimaSenetleriGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.TarifeGetirResponse> ReferansVerileri.IGumrukReferansVerileri.TarifeGetirAsync(ReferansVerileri.TarifeGetirRequest request)
        {
            return base.Channel.TarifeGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.TarifeGetirResponse> TarifeGetirAsync(string GTIP)
        {
            ReferansVerileri.TarifeGetirRequest inValue = new ReferansVerileri.TarifeGetirRequest();
            inValue.GTIP = GTIP;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).TarifeGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.FirmaBilgisiGetirResponse> ReferansVerileri.IGumrukReferansVerileri.FirmaBilgisiGetirAsync(ReferansVerileri.FirmaBilgisiGetirRequest request)
        {
            return base.Channel.FirmaBilgisiGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.FirmaBilgisiGetirResponse> FirmaBilgisiGetirAsync(string FirmaKimlikNo)
        {
            ReferansVerileri.FirmaBilgisiGetirRequest inValue = new ReferansVerileri.FirmaBilgisiGetirRequest();
            inValue.FirmaKimlikNo = FirmaKimlikNo;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).FirmaBilgisiGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.BankaBilgisiGetirResponse> ReferansVerileri.IGumrukReferansVerileri.BankaBilgisiGetirAsync(ReferansVerileri.BankaBilgisiGetirRequest request)
        {
            return base.Channel.BankaBilgisiGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.BankaBilgisiGetirResponse> BankaBilgisiGetirAsync(string bankaKodu)
        {
            ReferansVerileri.BankaBilgisiGetirRequest inValue = new ReferansVerileri.BankaBilgisiGetirRequest();
            inValue.bankaKodu = bankaKodu;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).BankaBilgisiGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferansVerileri.AntrepoBeyannamesiDogrumuResponse> ReferansVerileri.IGumrukReferansVerileri.AntrepoBeyannamesiDogrumuAsync(ReferansVerileri.AntrepoBeyannamesiDogrumuRequest request)
        {
            return base.Channel.AntrepoBeyannamesiDogrumuAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferansVerileri.AntrepoBeyannamesiDogrumuResponse> AntrepoBeyannamesiDogrumuAsync(string antrepoBeyannamesiNo)
        {
            ReferansVerileri.AntrepoBeyannamesiDogrumuRequest inValue = new ReferansVerileri.AntrepoBeyannamesiDogrumuRequest();
            inValue.antrepoBeyannamesiNo = antrepoBeyannamesiNo;
            return ((ReferansVerileri.IGumrukReferansVerileri)(this)).AntrepoBeyannamesiDogrumuAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGumrukReferansVerileri))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGumrukReferansVerileri))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.gtb.gov.tr:8080/EXT/Gumruk/GumrukReferansVeri/Provider/GumrukReferansVe" +
                        "rileriWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GumrukReferansVerileriClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGumrukReferansVerileri);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GumrukReferansVerileriClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGumrukReferansVerileri);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGumrukReferansVerileri,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
