//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYT.UI.OzetBeyanHizmeti {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gumruk.BizTalk.Integration", ConfigurationName="OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap")]
    public interface Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOz" +
            "etBeyanTalep/OzetBeyan", ReplyAction="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOz" +
            "etBeyanTalep/OzetBeyan")]
        BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut OzetBeyan(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOz" +
            "etBeyanTalep/OzetBeyan", ReplyAction="http://Gumruk.BizTalk.Integration/Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOz" +
            "etBeyanTalep/OzetBeyan")]
        System.Threading.Tasks.Task<BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut> OzetBeyanAsync(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OzetBeyanSoapIn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OzetBeyan", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapInBody Body;
        
        public OzetBeyanSoapIn() {
        }
        
        public OzetBeyanSoapIn(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapInBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class OzetBeyanSoapInBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Root;
        
        public OzetBeyanSoapInBody() {
        }
        
        public OzetBeyanSoapInBody(System.Xml.Linq.XElement Root) {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OzetBeyanSoapOut {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OzetBeyanResponse", Namespace="http://Gumruk.BizTalk.Integration", Order=0)]
        public BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOutBody Body;
        
        public OzetBeyanSoapOut() {
        }
        
        public OzetBeyanSoapOut(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
    public partial class OzetBeyanSoapOutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Root;
        
        public OzetBeyanSoapOutBody() {
        }
        
        public OzetBeyanSoapOutBody(System.Xml.Linq.XElement Root) {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapChannel : BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient : System.ServiceModel.ClientBase<BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap>, BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap {
        
        public Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient() {
        }
        
        public Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap.OzetBeyan(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn request) {
            return base.Channel.OzetBeyan(request);
        }
        
        public void OzetBeyan(ref System.Xml.Linq.XElement Root) {
            BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn inValue = new BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn();
            inValue.Body = new BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapInBody();
            inValue.Body.Root = Root;
            BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut retVal = ((BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap)(this)).OzetBeyan(inValue);
            Root = retVal.Body.Root;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut> BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap.OzetBeyanAsync(BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn request) {
            return base.Channel.OzetBeyanAsync(request);
        }
        
        public System.Threading.Tasks.Task<BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapOut> OzetBeyanAsync(System.Xml.Linq.XElement Root) {
            BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn inValue = new BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapIn();
            inValue.Body = new BYT.UI.OzetBeyanHizmeti.OzetBeyanSoapInBody();
            inValue.Body.Root = Root;
            return ((BYT.UI.OzetBeyanHizmeti.Gumruk_Biztalk_EImzaTescil_YeniOzetBeyan_YeniOzetBeyanTalepSoap)(this)).OzetBeyanAsync(inValue);
        }
    }
}
