//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYT.UI.SonucHizmeti {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SonucHizmeti.GumrukWSSoap")]
    public interface GumrukWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSorgula(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string IslemSonucu, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string IslemSonucu, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSorgula1(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula1Async(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSorgula2(string KullaniciAdi, string KullaniciSifre, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula2Async(string KullaniciAdi, string KullaniciSifre, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSorgula3(string KullaniciAdi, string KullaniciSifre, string RefID, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSorgula3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula3Async(string KullaniciAdi, string KullaniciSifre, string RefID, string BasIslemGunu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSonucGetir(string GUIDof, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetirAsync(string GUIDof, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSonucGetir1(string RefID, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir1Async(string RefID, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSonucGetir2(string GUIDof, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir2Async(string GUIDof, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSonucGetir3(string RefID, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir3Async(string RefID, string KullaniciAdi, string KullaniciSifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IslemSonucGetir4(string GUIDof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemSonucGetir4", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir4Async(string GUIDof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonuclanmamisIslemdekiMesajiIptalet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SonuclanmamisIslemdekiMesajiIptalet(string KullaniciAdi, string KullaniciSifre, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonuclanmamisIslemdekiMesajiIptalet", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SonuclanmamisIslemdekiMesajiIptaletAsync(string KullaniciAdi, string KullaniciSifre, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemdeKalmisGeciciNumaraSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IslemdeKalmisGeciciNumaraSil(string KullaniciAdi, string KullaniciSifre, string Beyanname_No, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemdeKalmisGeciciNumaraSil", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IslemdeKalmisGeciciNumaraSilAsync(string KullaniciAdi, string KullaniciSifre, string Beyanname_No, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TescilSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TescilSorgula(string KullaniciAdi, string KullaniciSifre, string GUID, string Gumruk, string Müsavir_referansi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TescilSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string GUID, string Gumruk, string Müsavir_referansi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanTescilSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ozetBeyanTescilSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanTescilSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanTescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanTescilSorgulaEmsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ozetBeyanTescilSorgulaEmsg(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanTescilSorgulaEmsg", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanTescilSorgulaEmsgAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanDurumSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ozetBeyanDurumSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozetBeyanDurumSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanDurumSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozbyMuayeneMemuruAdiSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ozbyMuayeneMemuruAdiSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ozbyMuayeneMemuruAdiSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ozbyMuayeneMemuruAdiSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tasinanOzbyBilgiSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet tasinanOzbyBilgiSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string VergiNo, string TasitNo, string ReferansNo, string BasTarihi, string BitTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tasinanOzbyBilgiSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> tasinanOzbyBilgiSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string VergiNo, string TasitNo, string ReferansNo, string BasTarihi, string BitTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tasinanOzbyBilgiSorgulaTsNoyaGore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet tasinanOzbyBilgiSorgulaTsNoyaGore(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TasimaSenediNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tasinanOzbyBilgiSorgulaTsNoyaGore", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> tasinanOzbyBilgiSorgulaTsNoyaGoreAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TasimaSenediNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mesajSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mesajSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mesajSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mesajSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aktarmaTescilSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet aktarmaTescilSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string BasTarihi, string BitTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aktarmaTescilSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> aktarmaTescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string BasTarihi, string BitTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGHBSonucSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IGHBSonucSorgula(string KullaniciAdi, string KullaniciSifre, string VergiNo, string IGHBNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGHBSonucSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IGHBSonucSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string VergiNo, string IGHBNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MesaiBasvuruSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MesaiBasvuruSorgula(string KullaniciAdi, string KullaniciSifre, System.DateTime BaslangicTarihi, System.DateTime BitisTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MesaiBasvuruSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MesaiBasvuruSorgulaAsync(string KullaniciAdi, string KullaniciSifre, System.DateTime BaslangicTarihi, System.DateTime BitisTarihi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GumrukWSSoapChannel : BYT.UI.SonucHizmeti.GumrukWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GumrukWSSoapClient : System.ServiceModel.ClientBase<BYT.UI.SonucHizmeti.GumrukWSSoap>, BYT.UI.SonucHizmeti.GumrukWSSoap {
        
        public GumrukWSSoapClient() {
        }
        
        public GumrukWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GumrukWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GumrukWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GumrukWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet IslemSorgula(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string IslemSonucu, string BasIslemGunu) {
            return base.Channel.IslemSorgula(KullaniciAdi, KullaniciSifre, IslemTipi, IslemSonucu, BasIslemGunu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string IslemSonucu, string BasIslemGunu) {
            return base.Channel.IslemSorgulaAsync(KullaniciAdi, KullaniciSifre, IslemTipi, IslemSonucu, BasIslemGunu);
        }
        
        public System.Data.DataSet IslemSorgula1(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string BasIslemGunu) {
            return base.Channel.IslemSorgula1(KullaniciAdi, KullaniciSifre, IslemTipi, BasIslemGunu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula1Async(string KullaniciAdi, string KullaniciSifre, string IslemTipi, string BasIslemGunu) {
            return base.Channel.IslemSorgula1Async(KullaniciAdi, KullaniciSifre, IslemTipi, BasIslemGunu);
        }
        
        public System.Data.DataSet IslemSorgula2(string KullaniciAdi, string KullaniciSifre, string BasIslemGunu) {
            return base.Channel.IslemSorgula2(KullaniciAdi, KullaniciSifre, BasIslemGunu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula2Async(string KullaniciAdi, string KullaniciSifre, string BasIslemGunu) {
            return base.Channel.IslemSorgula2Async(KullaniciAdi, KullaniciSifre, BasIslemGunu);
        }
        
        public System.Data.DataSet IslemSorgula3(string KullaniciAdi, string KullaniciSifre, string RefID, string BasIslemGunu) {
            return base.Channel.IslemSorgula3(KullaniciAdi, KullaniciSifre, RefID, BasIslemGunu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSorgula3Async(string KullaniciAdi, string KullaniciSifre, string RefID, string BasIslemGunu) {
            return base.Channel.IslemSorgula3Async(KullaniciAdi, KullaniciSifre, RefID, BasIslemGunu);
        }
        
        public System.Data.DataSet IslemSonucGetir(string GUIDof, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir(GUIDof, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetirAsync(string GUIDof, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetirAsync(GUIDof, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Data.DataSet IslemSonucGetir1(string RefID, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir1(RefID, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir1Async(string RefID, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir1Async(RefID, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Data.DataSet IslemSonucGetir2(string GUIDof, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir2(GUIDof, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir2Async(string GUIDof, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir2Async(GUIDof, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Data.DataSet IslemSonucGetir3(string RefID, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir3(RefID, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir3Async(string RefID, string KullaniciAdi, string KullaniciSifre) {
            return base.Channel.IslemSonucGetir3Async(RefID, KullaniciAdi, KullaniciSifre);
        }
        
        public System.Data.DataSet IslemSonucGetir4(string GUIDof) {
            return base.Channel.IslemSonucGetir4(GUIDof);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IslemSonucGetir4Async(string GUIDof) {
            return base.Channel.IslemSonucGetir4Async(GUIDof);
        }
        
        public string SonuclanmamisIslemdekiMesajiIptalet(string KullaniciAdi, string KullaniciSifre, string GUID) {
            return base.Channel.SonuclanmamisIslemdekiMesajiIptalet(KullaniciAdi, KullaniciSifre, GUID);
        }
        
        public System.Threading.Tasks.Task<string> SonuclanmamisIslemdekiMesajiIptaletAsync(string KullaniciAdi, string KullaniciSifre, string GUID) {
            return base.Channel.SonuclanmamisIslemdekiMesajiIptaletAsync(KullaniciAdi, KullaniciSifre, GUID);
        }
        
        public string IslemdeKalmisGeciciNumaraSil(string KullaniciAdi, string KullaniciSifre, string Beyanname_No, string GUID) {
            return base.Channel.IslemdeKalmisGeciciNumaraSil(KullaniciAdi, KullaniciSifre, Beyanname_No, GUID);
        }
        
        public System.Threading.Tasks.Task<string> IslemdeKalmisGeciciNumaraSilAsync(string KullaniciAdi, string KullaniciSifre, string Beyanname_No, string GUID) {
            return base.Channel.IslemdeKalmisGeciciNumaraSilAsync(KullaniciAdi, KullaniciSifre, Beyanname_No, GUID);
        }
        
        public System.Data.DataSet TescilSorgula(string KullaniciAdi, string KullaniciSifre, string GUID, string Gumruk, string Müsavir_referansi) {
            return base.Channel.TescilSorgula(KullaniciAdi, KullaniciSifre, GUID, Gumruk, Müsavir_referansi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string GUID, string Gumruk, string Müsavir_referansi) {
            return base.Channel.TescilSorgulaAsync(KullaniciAdi, KullaniciSifre, GUID, Gumruk, Müsavir_referansi);
        }
        
        public System.Data.DataSet ozetBeyanTescilSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih) {
            return base.Channel.ozetBeyanTescilSorgula(KullaniciAdi, KullaniciSifre, Gumruk, tarih);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanTescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih) {
            return base.Channel.ozetBeyanTescilSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, tarih);
        }
        
        public System.Data.DataSet ozetBeyanTescilSorgulaEmsg(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih) {
            return base.Channel.ozetBeyanTescilSorgulaEmsg(KullaniciAdi, KullaniciSifre, Gumruk, tarih);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanTescilSorgulaEmsgAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string tarih) {
            return base.Channel.ozetBeyanTescilSorgulaEmsgAsync(KullaniciAdi, KullaniciSifre, Gumruk, tarih);
        }
        
        public System.Data.DataSet ozetBeyanDurumSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.ozetBeyanDurumSorgula(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ozetBeyanDurumSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.ozetBeyanDurumSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Data.DataSet ozbyMuayeneMemuruAdiSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.ozbyMuayeneMemuruAdiSorgula(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ozbyMuayeneMemuruAdiSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.ozbyMuayeneMemuruAdiSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Data.DataSet tasinanOzbyBilgiSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string VergiNo, string TasitNo, string ReferansNo, string BasTarihi, string BitTarihi) {
            return base.Channel.tasinanOzbyBilgiSorgula(KullaniciAdi, KullaniciSifre, Gumruk, VergiNo, TasitNo, ReferansNo, BasTarihi, BitTarihi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> tasinanOzbyBilgiSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string VergiNo, string TasitNo, string ReferansNo, string BasTarihi, string BitTarihi) {
            return base.Channel.tasinanOzbyBilgiSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, VergiNo, TasitNo, ReferansNo, BasTarihi, BitTarihi);
        }
        
        public System.Data.DataSet tasinanOzbyBilgiSorgulaTsNoyaGore(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TasimaSenediNo) {
            return base.Channel.tasinanOzbyBilgiSorgulaTsNoyaGore(KullaniciAdi, KullaniciSifre, Gumruk, TasimaSenediNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> tasinanOzbyBilgiSorgulaTsNoyaGoreAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TasimaSenediNo) {
            return base.Channel.tasinanOzbyBilgiSorgulaTsNoyaGoreAsync(KullaniciAdi, KullaniciSifre, Gumruk, TasimaSenediNo);
        }
        
        public System.Data.DataSet mesajSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.mesajSorgula(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mesajSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string TescilNo) {
            return base.Channel.mesajSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, TescilNo);
        }
        
        public System.Data.DataSet aktarmaTescilSorgula(string KullaniciAdi, string KullaniciSifre, string Gumruk, string BasTarihi, string BitTarihi) {
            return base.Channel.aktarmaTescilSorgula(KullaniciAdi, KullaniciSifre, Gumruk, BasTarihi, BitTarihi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> aktarmaTescilSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string Gumruk, string BasTarihi, string BitTarihi) {
            return base.Channel.aktarmaTescilSorgulaAsync(KullaniciAdi, KullaniciSifre, Gumruk, BasTarihi, BitTarihi);
        }
        
        public System.Data.DataSet IGHBSonucSorgula(string KullaniciAdi, string KullaniciSifre, string VergiNo, string IGHBNo) {
            return base.Channel.IGHBSonucSorgula(KullaniciAdi, KullaniciSifre, VergiNo, IGHBNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IGHBSonucSorgulaAsync(string KullaniciAdi, string KullaniciSifre, string VergiNo, string IGHBNo) {
            return base.Channel.IGHBSonucSorgulaAsync(KullaniciAdi, KullaniciSifre, VergiNo, IGHBNo);
        }
        
        public System.Data.DataSet MesaiBasvuruSorgula(string KullaniciAdi, string KullaniciSifre, System.DateTime BaslangicTarihi, System.DateTime BitisTarihi) {
            return base.Channel.MesaiBasvuruSorgula(KullaniciAdi, KullaniciSifre, BaslangicTarihi, BitisTarihi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MesaiBasvuruSorgulaAsync(string KullaniciAdi, string KullaniciSifre, System.DateTime BaslangicTarihi, System.DateTime BitisTarihi) {
            return base.Channel.MesaiBasvuruSorgulaAsync(KullaniciAdi, KullaniciSifre, BaslangicTarihi, BitisTarihi);
        }
    }
}
