//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYT.UI.IGHBHizmeti {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Gumruk.BizTalk.Integration", ConfigurationName="IGHBHizmeti.Gumruk_Biztalk_IGHB")]
    public interface Gumruk_Biztalk_IGHB {
        
        // CODEGEN: Generating message contract since the wrapper name (IGHB) of message IGHBSoapIn does not match the default value (IzinliGondericiHazirBildirimiYap)
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi", ReplyAction="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BYT.UI.IGHBHizmeti.IGHBSoapOut IzinliGondericiHazirBildirimiYap(BYT.UI.IGHBHizmeti.IGHBSoapIn request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi", ReplyAction="http://Gumruk.BizTalk.Integration/IzinliGondericiHazirBildirimi")]
        System.Threading.Tasks.Task<BYT.UI.IGHBHizmeti.IGHBSoapOut> IzinliGondericiHazirBildirimiYapAsync(BYT.UI.IGHBHizmeti.IGHBSoapIn request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://LoginKontrol.IGHBGelen")]
    public partial class IGHBGelen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refIDField;
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        private IGHB iGHBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RefID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
                this.RaisePropertyChanged("RefID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", IsNullable=true, Order=3)]
        public IGHB IGHB {
            get {
                return this.iGHBField;
            }
            set {
                this.iGHBField = value;
                this.RaisePropertyChanged("IGHB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IGHB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tesisKoduField;
        
        private string izinliGondericiVergiNoField;
        
        private string gumrukKoduField;
        
        private string plakaBilgisiField;
        
        private TCGBBilgi[] tCGBBilgiListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TesisKodu {
            get {
                return this.tesisKoduField;
            }
            set {
                this.tesisKoduField = value;
                this.RaisePropertyChanged("TesisKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IzinliGondericiVergiNo {
            get {
                return this.izinliGondericiVergiNoField;
            }
            set {
                this.izinliGondericiVergiNoField = value;
                this.RaisePropertyChanged("IzinliGondericiVergiNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GumrukKodu {
            get {
                return this.gumrukKoduField;
            }
            set {
                this.gumrukKoduField = value;
                this.RaisePropertyChanged("GumrukKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PlakaBilgisi {
            get {
                return this.plakaBilgisiField;
            }
            set {
                this.plakaBilgisiField = value;
                this.RaisePropertyChanged("PlakaBilgisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        public TCGBBilgi[] TCGBBilgiListesi {
            get {
                return this.tCGBBilgiListesiField;
            }
            set {
                this.tCGBBilgiListesiField = value;
                this.RaisePropertyChanged("TCGBBilgiListesi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGBBilgi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tCGBNumarasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TCGBNumarasi {
            get {
                return this.tCGBNumarasiField;
            }
            set {
                this.tCGBNumarasiField = value;
                this.RaisePropertyChanged("TCGBNumarasi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IGHB", WrapperNamespace="http://Gumruk.BizTalk.Integration", IsWrapped=true)]
    public partial class IGHBSoapIn {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://LoginKontrol.IGHBGelen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://LoginKontrol.IGHBGelen")]
        public BYT.UI.IGHBHizmeti.IGHBGelen IGHBGelen;
        
        public IGHBSoapIn() {
        }
        
        public IGHBSoapIn(BYT.UI.IGHBHizmeti.IGHBGelen IGHBGelen) {
            this.IGHBGelen = IGHBGelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IGHBResponse", WrapperNamespace="http://Gumruk.BizTalk.Integration", IsWrapped=true)]
    public partial class IGHBSoapOut {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.microsoft.com/BizTalk/2003/Any")]
        public System.Xml.XmlNode Root;
        
        public IGHBSoapOut() {
        }
        
        public IGHBSoapOut(System.Xml.XmlNode Root) {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Gumruk_Biztalk_IGHBChannel : BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Gumruk_Biztalk_IGHBClient : System.ServiceModel.ClientBase<BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB>, BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB {
        
        public Gumruk_Biztalk_IGHBClient() {
        }
        
        public Gumruk_Biztalk_IGHBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Gumruk_Biztalk_IGHBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_IGHBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Gumruk_Biztalk_IGHBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BYT.UI.IGHBHizmeti.IGHBSoapOut BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB.IzinliGondericiHazirBildirimiYap(BYT.UI.IGHBHizmeti.IGHBSoapIn request) {
            return base.Channel.IzinliGondericiHazirBildirimiYap(request);
        }
        
        public System.Xml.XmlNode IzinliGondericiHazirBildirimiYap(BYT.UI.IGHBHizmeti.IGHBGelen IGHBGelen) {
            BYT.UI.IGHBHizmeti.IGHBSoapIn inValue = new BYT.UI.IGHBHizmeti.IGHBSoapIn();
            inValue.IGHBGelen = IGHBGelen;
            BYT.UI.IGHBHizmeti.IGHBSoapOut retVal = ((BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB)(this)).IzinliGondericiHazirBildirimiYap(inValue);
            return retVal.Root;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BYT.UI.IGHBHizmeti.IGHBSoapOut> BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB.IzinliGondericiHazirBildirimiYapAsync(BYT.UI.IGHBHizmeti.IGHBSoapIn request) {
            return base.Channel.IzinliGondericiHazirBildirimiYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<BYT.UI.IGHBHizmeti.IGHBSoapOut> IzinliGondericiHazirBildirimiYapAsync(BYT.UI.IGHBHizmeti.IGHBGelen IGHBGelen) {
            BYT.UI.IGHBHizmeti.IGHBSoapIn inValue = new BYT.UI.IGHBHizmeti.IGHBSoapIn();
            inValue.IGHBGelen = IGHBGelen;
            return ((BYT.UI.IGHBHizmeti.Gumruk_Biztalk_IGHB)(this)).IzinliGondericiHazirBildirimiYapAsync(inValue);
        }
    }
}
